name: Deploy 23Chat App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_MIKRUS_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -p 10605 chat-23-net-pl@frog02.mikr.us << 'EOF'
            cd /home/chat-23-net-pl
            git pull origin main
            # rc-service chat-23-net-pl restart
            # Restart the app if needed, e.g., pm2 restart chat-app or systemctl restart chat-app
          EOF
